---
id: chuork01-booklet
base_name: timetable-and-introduction
tags:
- chuork01
presentation_date: 
version: 0.0.1
licenses:
- CC BY-ND 3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: "札幌市中央区Ruby会議01実行委員会"
  email: myokoym@gmail.com
  rubygems_user: 
  slideshare_user: 
  speaker_deck_user: 
